site_links:
  home_logo: "/assets/img/logo.svg"   # 無ければ一旦適当な画像でOK
  github: "https://github.com/SnowFairyTea"
  twitter: "https://x.com/SnowFairyTea"

title: SnowFairyTea
logo_lines:
  - text: SnowFairyTea
    size: large
  - text: Playground
    size: small

description: Personal playground / demos / notes
theme: null
plugins: []

google_fonts_url: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600&family=Montserrat:wght@500;600&display=swap"

url: "https://snowfairytea.dev"
baseurl: ""

Links:
  # - service: Steam
  #   name: fairy
  #   id: 869863946
  #   url: 

  - service: GitHub
    name: SnowFairyTea
    url: https://github.com/SnowFairyTea

  - service: X
    name: SnowFairyTea
    url: https://x.com/SnowFairyTea

  - service: 良かったものリスト
    name: 工事中
    url: "#"

  - service: ほしいものリスト（ポケモンGO）
    name: 工事中
    url: "#"
accounts:
  # - service: Steam
  #   name: fairy
  #   id: 869863946
  #   url: https://steamcommunity.com/profiles/869863946
  - service: pokemon GO
    name: Snowfairy2002
    id: 206082336128
